#ifndef BPU_CONSTANTS_H
#define BPU_CONSTANTS_H

constexpr int REGISTER_FILE_SIZE = 12;
constexpr int MEMORY_CYCLES_DELAY = 2;
constexpr int PIPELINE_STAGES = 4;
constexpr int MEMORY_SIZE = 512;
constexpr int COMPLETION_DELAY = PIPELINE_STAGES * MEMORY_CYCLES_DELAY * 2;

#endif //BPU_CONSTANTS_H
